channel: /dev/ttyACM0
gripper:
- name: gripper
  motor_id: 7
  feedback_id: 23
  model: '4310'
  vendor: damiao
  limit_lower_deg: -85.6
  limit_upper_deg: 0.1
  MIT:
    kp: 8.0
    kd: 1.0
  POS_VEL:
    vel_kp: 0.0008
    vel_ki: 0.002
    pos_kp: 50.0
    pos_ki: 1.0
    vlim: 3.0
